# Generated by Django 3.2.8 on 2021-10-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.FloatField(default=0.0)),
                ('gu', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=50)),
            ],
        ),
    ]
