# Generated by Django 3.2.8 on 2021-10-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
