# Generated by Django 3.2.8 on 2021-10-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0002_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50)),
                ('gu', models.CharField(max_length=70)),
                ('detail', models.CharField(max_length=70)),
            ],
        ),
    ]
