# Generated by Django 3.2.8 on 2021-10-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_places'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Places',
        ),
    ]
