# Generated by Django 3.2.8 on 2021-11-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0004_delete_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=70)),
                ('gu', models.CharField(max_length=70)),
                ('detail', models.CharField(max_length=80)),
            ],
        ),
    ]
